pub mod challenge_4_1_temperature_converter_with_methods;
pub mod challenge_4_2_selective_processing_with_if_let;
pub mod challenge_4_3_happy_path_with_let_else;
pub mod challenge_4_4_vehicle_fleet_analyzer;
